<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
/**
 * This file is generated by Webpack, do not edit it directly.
 */
return [
	'handle' => 'elementor-v2-editor-variables',
	'deps' => [
		'elementor-v2-editor',
		'elementor-v2-editor-canvas',
		'elementor-v2-editor-controls',
		'elementor-v2-editor-current-user',
		'elementor-v2-editor-editing-panel',
		'elementor-v2-editor-mcp',
		'elementor-v2-editor-panels',
		'elementor-v2-editor-props',
		'elementor-v2-editor-ui',
		'elementor-v2-editor-v1-adapters',
		'elementor-v2-http-client',
		'elementor-v2-icons',
		'elementor-v2-mixpanel',
		'elementor-v2-schema',
		'elementor-v2-ui',
<<<<<<< HEAD
		'elementor-v2-utils',
=======
>>>>>>> 925a27b3365a70f9d425839bd2b9f9ff46969275
		'react',
		'wp-i18n',
	],
];
