<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
/**
 * This file is generated by Webpack, do not edit it directly.
 */
return [
	'handle' => 'elementor-v2-editor-mcp',
	'deps' => [
		'elementor-v2-editor-v1-adapters',
<<<<<<< HEAD
		'elementor-v2-schema',
=======
>>>>>>> 925a27b3365a70f9d425839bd2b9f9ff46969275
	],
];
